apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: exercises
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  clusterIP: None
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-stset
  namespace: exercises
spec:
  serviceName: postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - name: web
              containerPort: 5432
          volumeMounts:
            - name: postgres-db
              mountPath: /var/lib/postgresql
          env:
            - name: POSTGRES_HOST
              value: postgres-svc
            - name: POSTGRES_DB
              value: pingpongdb
            - name: POSTGRES_USER
              value: pingpong
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
  volumeClaimTemplates:
    - metadata:
        name: postgres-db
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
