apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: project
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  clusterIP: None
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-stset
  namespace: project
spec:
  selector:
    matchLabels:
      app: postgres-stset # has to match .spec.template.metadata.labels
  serviceName: "postgres-stset"
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  postgres-stset
      labels:
        app: postgres-stset # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-db
          mountPath: /var/lib/postgresql
        env:
          - name: POSTGRES_HOST
            value: postgres-svc
          - name: POSTGRES_DB
            value: pingpongdb
          - name: POSTGRES_USER
            value: pingpong
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password
  volumeClaimTemplates:
  - metadata:
      name: postgres-db
    spec:
      storageClassName: local-path
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Mi
---

